language: python
python:
  - "2.7.15"
  - "3.6"
  - "3.7"
virtualenv:
  system_site_packages: false

cache: pip

# command to install dependencies
before_install:
  - python setup.py sdist
install:
  - pip install -r requirements.txt
  - pip install ./dist/*
script:
  - python test.py

# command to run tests
#script:
