language: python
python:
  - "2.7.15"
  - "3.6"
  - "3.7"
virtualenv:
  system_site_packages: false

# command to install dependencies
before_install:
  - python setup.py sdist
install:
  - pip install -r requirements.txt
  - pip install ./dist/*
after_install:
  - python test.py

# command to run tests
#script:
